function fig = LiquidDispenserGUI()
% A GUI for controlling two valves (left/right) to dispense water droplets
% Features:
% - Set dose volume (μL) and number of drops for each valve
% - Real-time cumulative volume display (left, right, and total)
% - Clear counters function
% - Status feedback during operation

DefaultDropSize = 6;
DefaultLeftFreq = 100;
DefaultLeftAmp = 0.5;
DefaultRightFreq = 400;
DefaultRightAmp = 0.04;

% Create main window
fig = uifigure('Name', 'Liquid Dispensing Control System', ...
              'Position', [500 200 600 550], ...
              'Resize', 'off');

% Left control panel
leftPanel = uipanel(fig, 'Title', 'Left Valve (Valve 1)', ...
                   'Position', [50 230 220 240], ...
                   'FontSize', 14, ...
                   'FontWeight', 'bold');

% Left Volume setting
uilabel(leftPanel, 'Position', [20 190 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);
leftDoseField = uieditfield(leftPanel, 'numeric', ...
                           'Position', [120 190 80 25], ...
                           'Value', DefaultDropSize, ...
                           'Limits', [0.1 1000], ...
                           'FontSize', 20, ...
                           'ValueChangedFcn', @(txt,event) updateValveTime(fig, 'left'));

% Left number of drops setting
uilabel(leftPanel, 'Position', [20 155 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

leftDropField = uieditfield(leftPanel, 'numeric', ...
                            'Position', [120 155 80 25], ...
                            'Value', 1, ...
                            'Limits', [1 100], ...
                            'FontSize', 20);
% Left duration  setting
uilabel(leftPanel, 'Position', [20 120 100 20], ...
       'Text', 'Duration (ms):', ...
       'FontSize', 12);
ValveTime = BpodLiquidCalibration('GetValveTimes', DefaultDropSize, 1);

leftDurationField = uieditfield(leftPanel, 'numeric', ...
                            'Position', [120 120 80 25], ...
                            'Value', 1000*ValveTime, ...
                            'Limits', [0 1000], ...
                            'FontSize', 20, ...
                            'ValueDisplayFormat','%.0f',...
                            'Editable','off');
% Left dispense button
leftButton = uibutton(leftPanel, 'push', ...
                        'Position', [20 80 180 30], ...
                     'Text', 'Left Dispense (''A'')', ...
                     'FontSize', 14, ...
                     'FontWeight', 'bold', ...
                     'BackgroundColor', [0.3 0.7 0.9], ...
                     'ButtonPushedFcn', @(btn,event) leftDispense(fig));
% Stimulus
    leftStimulusCheckBox = uicheckbox(leftPanel, ...
                          'Position', [20 50 180 22], ...
                          'Text', 'add vibration', ...
                          'Value', false);
    uilabel(leftPanel, 'Position', [20 20 60 25], ...
        'Text', 'Freq (Hz):', ...
        'FontSize', 12);
    leftVibFreqField = uieditfield(leftPanel, 'numeric', ...
                       'Position', [75 20 45 25], ...
                       'Value', DefaultLeftFreq, ...
                       'Limits', [20 80000], ...
                       'ValueDisplayFormat', '%.0f');
    uilabel(leftPanel, 'Position', [125 20 35 25], ...
        'Text', 'Amp:', ...
        'FontSize', 12);
    leftVibAmpField = uieditfield(leftPanel, 'numeric', ...
                      'Position', [160 20 50 25], ...
                      'Value', DefaultLeftAmp, ...
                      'Limits', [0 1], ...
                      'ValueDisplayFormat', '%.3f');





% uilabel(leftPanel, 'Position', [20 20 180 20], ...
%        'Text', 'Click "A" to dispense', ...
%        'HorizontalAlignment','center',...
%        'FontSize', 16);


% Right control panel
rightPanel = uipanel(fig, 'Title', 'Right Valve (Valve 2)', ...
              'Position', [330 230 220 240], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Right Volume setting
uilabel(rightPanel, 'Position', [20 190 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);

rightDoseField = uieditfield(rightPanel, 'numeric', ...
                'Position', [120 190 80 25], ...
                            'Value', DefaultDropSize, ...
                            'Limits', [0.1 1000], ...
                            'FontSize', 20, ...
                            'ValueChangedFcn', @(txt,event) updateValveTime(fig, 'right'));

% Right number of drops setting
uilabel(rightPanel, 'Position', [20 155 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

rightDropField = uieditfield(rightPanel, 'numeric', ...
                             'Position', [120 155 80 25], ...
                             'Value', 1, ...
                             'Limits', [1 100], ...
                             'FontSize', 20);

% Right duration  setting
uilabel(rightPanel, 'Position', [20 120 100 20], ...
       'Text', 'Duration (ms):', ...
       'FontSize', 12);
ValveTime = BpodLiquidCalibration('GetValveTimes', DefaultDropSize, 2);

rightDurationField = uieditfield(rightPanel, 'numeric', ...
                            'Position', [120 120 80 25], ...
                            'Value', 1000*ValveTime, ...
                            'Limits', [0 1000], ...
                            'FontSize', 20, ...
                            'ValueDisplayFormat','%.0f',...
                            'Editable','off');

rightButton = uibutton(rightPanel, 'push', ...
                       'Position', [20 80 180 30], ...
                       'Text', 'Right Dispense (''D'')', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.3 0.7 0.9], ...
                       'ButtonPushedFcn', @(btn,event) rightDispense(fig));

rightStimulusCheckBox = uicheckbox(rightPanel, ...
                                   'Position', [20 50 180 22], ...
                                   'Text', 'add vibration', ...
                                   'Value', false);
uilabel(rightPanel, 'Position', [20 20 60 25], ...
        'Text', 'Freq (Hz):', ...
        'FontSize', 12);
rightVibFreqField = uieditfield(rightPanel, 'numeric', ...
                                'Position', [75 20 45 25], ...
                                'Value', DefaultRightFreq, ...
                                'Limits', [20 80000], ...
                                'ValueDisplayFormat', '%.0f');
uilabel(rightPanel, 'Position', [125 20 35 25], ...
        'Text', 'Amp:', ...
        'FontSize', 12);
rightVibAmpField = uieditfield(rightPanel, 'numeric', ...
                               'Position', [160 20 50 25], ...
                               'Value', DefaultRightAmp, ...
                               'Limits', [0 1], ...
                               'ValueDisplayFormat', '%.3f');

% uilabel(rightPanel, 'Position', [20 20 180 20], ...
%        'Text', 'Click "D" to dispense', ...
%        'HorizontalAlignment','center',...
%        'FontSize', 12);


% Counter display panel
countPanel = uipanel(fig, 'Title', 'Cumulative Dispensed Volume', ...
                    'Position', [50 70 500 150], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Left counter display
uilabel(countPanel, 'Position', [80 80 100 30], ...
       'Text', 'Left Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

leftCountLabel = uilabel(countPanel, 'Position', [200 80 100 30], ...
                        'Text', '0 μL', ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold', ...
                        'FontColor', [0 0.5 0]);

% Right counter display
uilabel(countPanel, 'Position', [300 80 100 30], ...
       'Text', 'Right Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

rightCountLabel = uilabel(countPanel, 'Position', [420 80 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0 0.5 0]);

% Total counter display
uilabel(countPanel, 'Position', [150 30 100 30], ...
       'Text', 'Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold', ...
       'FontColor', [0.5 0 0.5]);

totalCountLabel = uilabel(countPanel, 'Position', [250 30 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0.5 0 0.5]);

% Clear button
clearButton = uibutton(countPanel, 'push', ...
                      'Position', [350 30 100 30], ...
                      'Text', 'Clear Counters', ...
                      'FontSize', 12, ...
                      'BackgroundColor', [0.9 0.9 0.9], ...
                      'ButtonPushedFcn', @(btn,event) clearCounters(fig));

% Status display
statusLabel = uilabel(fig, 'Position', [50 20 500 30], ...
                     'Text', 'Ready', ...
                     'FontSize', 12, ...
                     'HorizontalAlignment', 'center', ...
                     'BackgroundColor', [0.95 0.95 0.95]);
% Initialize HiFi module
try
    H = BpodHiFi('COM3');
    H.SamplingRate = 192000;
catch
    disp('HiFi Module not connected.')
    H = [];
end

data = struct('leftCount', 0, ...
              'rightCount', 0, ...
              'totalCount', 0, ...
              'leftDoseField', leftDoseField, ...
              'leftDropField', leftDropField, ...
              'leftDurationField', leftDurationField, ...
              'leftVibAmpField', leftVibAmpField, ...
              'leftVibFreqField', leftVibFreqField, ...
              'leftStimulusCheckBox', leftStimulusCheckBox, ...
              'rightDoseField', rightDoseField, ...
              'rightDropField', rightDropField, ...
              'rightDurationField', rightDurationField, ...
              'rightVibAmpField', rightVibAmpField, ...
              'rightVibFreqField', rightVibFreqField, ...
              'rightStimulusCheckBox', rightStimulusCheckBox, ...
              'leftCountLabel', leftCountLabel, ...
              'rightCountLabel', rightCountLabel, ...
              'totalCountLabel', totalCountLabel, ...
              'statusLabel', statusLabel,...
              'HiFiModule',H);
guidata(fig, data);

fig.CloseRequestFcn = @(src,event) closeGUI(fig);
fig.KeyPressFcn = @(src, event) onKeyPress(src, event);


function onKeyPress(fig, event)
    % event.Key contains the name of the key pressed
    % event.Modifier contains any modifier keys (e.g., 'shift', 'control')
    keyName = event.Key;
    modifiers = strjoin(event.Modifier, '+');

switch keyName
    case {'a'}
        leftDispense(fig)
    case {'d'}
        rightDispense(fig)
end
%     if isempty(modifiers)
%         statusLabel.Text = sprintf('You pressed: %s', keyName);
%     else
%         statusLabel.Text = sprintf('You pressed: %s + %s', modifiers, keyName);
%     end
end

% Left dispense function
function leftDispense(fig)
    data = guidata(fig);
    addStimulus = data.leftStimulusCheckBox.Value;
    try
        dose = data.leftDoseField.Value;
        drops = data.leftDropField.Value;
        ValveTime_s = data.leftDurationField.Value ./ 1000;
        
        data.statusLabel.Text = 'Left dispensing in progress...';
        data.statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;

        if addStimulus
            setValveStimulus(data.HiFiModule, data.leftVibAmpField.Value, ...
                             data.leftVibFreqField.Value, true);
        end
        
        % Call dispense function
%         Dispense(1, dose, drops);
        DispenseByDur(1, ValveTime_s, drops);

        if addStimulus
            setValveStimulus(data.HiFiModule, 0, 0, false);
            addStimulus = false;
        end
        
        % Update counters
        dispensedVolume = dose * drops;
        data.leftCount = data.leftCount + dispensedVolume;
        data.totalCount = data.totalCount + dispensedVolume;
        guidata(fig, data);
        
        data.leftCountLabel.Text = [num2str(data.leftCount) ' μL'];
        data.totalCountLabel.Text = [num2str(data.totalCount) ' μL'];
        
        data.statusLabel.Text = sprintf('Left dispense complete: %.1f μL × %d', dose, drops);
        data.statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        if addStimulus
            try
                setValveStimulus(data.HiFiModule, 0, 0, false);
            catch
            end
        end
        data.statusLabel.Text = ['Error: ' ME.message];
        data.statusLabel.BackgroundColor = [1 0.8 0.8];
    end
end

% Right dispense function
function rightDispense(fig)
    data = guidata(fig);
    addStimulus = data.rightStimulusCheckBox.Value;
    try
        dose = data.rightDoseField.Value;
        drops = data.rightDropField.Value;
        ValveTime_s = data.rightDurationField.Value ./ 1000;
        
        data.statusLabel.Text = 'Right dispensing in progress...';
        data.statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;

        if addStimulus
            setValveStimulus(data.HiFiModule, data.rightVibAmpField.Value, ...
                             data.rightVibFreqField.Value, true);
        end
        
        % Call dispense function
%         Dispense(2, dose, drops);
        DispenseByDur(2, ValveTime_s, drops);

        if addStimulus
            setValveStimulus(data.HiFiModule, 0, 0, false);
            addStimulus = false;
        end
        
        % Update counters
        dispensedVolume = dose * drops;
        data.rightCount = data.rightCount + dispensedVolume;
        data.totalCount = data.totalCount + dispensedVolume;
        guidata(fig, data);
        
        data.rightCountLabel.Text = [num2str(data.rightCount) ' μL'];
        data.totalCountLabel.Text = [num2str(data.totalCount) ' μL'];
        
        data.statusLabel.Text = sprintf('Right dispense complete: %.1f μL × %d', dose, drops);
        data.statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        if addStimulus
            try
                setValveStimulus(data.HiFiModule, 0, 0, false);
            catch
            end
        end
        data.statusLabel.Text = ['Error: ' ME.message];
        data.statusLabel.BackgroundColor = [1 0.8 0.8];
    end
end

function setValveStimulus(hiFiModule, amplitude, frequency, enabled)
    if enabled
        hiFiModule.SynthAmplitude = 0;
        hiFiModule.SynthWaveform = 'Sine';
        hiFiModule.SynthFrequency = frequency;
        hiFiModule.SynthAmplitude = amplitude;
    else
        hiFiModule.SynthAmplitude = 0;
    end
end

% Clear counters function
function clearCounters(fig)
    data = guidata(fig);
    data.leftCount = 0;
    data.rightCount = 0;
    data.totalCount = 0;
    data.leftCountLabel.Text = '0 μL';
    data.rightCountLabel.Text = '0 μL';
    data.totalCountLabel.Text = '0 μL';
    data.statusLabel.Text = 'Counters cleared';
    data.statusLabel.BackgroundColor = [0.95 0.95 0.95];
    guidata(fig, data);
end

% Close GUI function - FIXED: now accepts fig as input argument
function closeGUI(fig)
    % Stop Bpod protocol
    try
        RunProtocol('Stop');
    catch
        % Ignore errors
    end
    delete(fig);
end

function updateValveTime(fig, whichValve)
    data = guidata(fig);
    switch whichValve
        case 'left'
            newDropSize_ul = data.leftDoseField.Value;
            newValveTime_s = BpodLiquidCalibration('GetValveTimes', newDropSize_ul, 1);
            data.leftDurationField.Value = 1000*newValveTime_s;
        case 'right'
            newDropSize_ul = data.rightDoseField.Value;
            newValveTime_s = BpodLiquidCalibration('GetValveTimes', newDropSize_ul, 2);
            data.rightDurationField.Value = 1000*newValveTime_s;

    end
end
end