% A GUI for controlling two valves (left/right) to dispense water droplets
% Features:
% - Set dose volume (μL) and number of drops for each valve
% - Real-time cumulative volume display (left, right, and total)
% - Clear counters function
% - Status feedback during operation

% Create main window
fig = uifigure('Name', 'Liquid Dispensing Control System', ...
              'Position', [500 300 600 550], ...
              'Resize', 'off');

% Initialize counter variables
global leftCount rightCount totalCount
global leftDoseField leftDropField rightDoseField rightDropField leftCountLabel rightCountLabel totalCountLabel statusLabel
global leftDurationField rightDurationField
leftCount = 0;
rightCount = 0;
totalCount = 0;


% Left control panel
leftPanel = uipanel(fig, 'Title', 'Left Valve (Valve 1)', ...
                   'Position', [50 300 220 200], ...
                   'FontSize', 14, ...
                   'FontWeight', 'bold');

% Left Volume setting
uilabel(leftPanel, 'Position', [20 140 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);
DefaultDropSize = 6;
leftDoseField = uieditfield(leftPanel, 'numeric', ...
                           'Position', [120 140 80 25], ...
                           'Value', DefaultDropSize, ...
                           'Limits', [0.1 1000], ...
                           'FontSize', 20, ...
                           'ValueChangedFcn', @(txt,event) updateValveTime('left'));

% Left number of drops setting
uilabel(leftPanel, 'Position', [20 100 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

leftDropField = uieditfield(leftPanel, 'numeric', ...
                            'Position', [120 100 80 25], ...
                            'Value', 1, ...
                            'Limits', [1 100], ...
                            'FontSize', 20);
% Left duration  setting
uilabel(leftPanel, 'Position', [20 60 100 20], ...
       'Text', 'Duration (ms):', ...
       'FontSize', 12);
ValveTime = BpodLiquidCalibration('GetValveTimes', DefaultDropSize, 1);

leftDurationField = uieditfield(leftPanel, 'numeric', ...
                            'Position', [120 60 80 25], ...
                            'Value', 1000*ValveTime, ...
                            'Limits', [0 1000], ...
                            'FontSize', 20, ...
                            'ValueDisplayFormat','%.0f',...
                            'Editable','off');

% Left dispense button
leftButton = uibutton(leftPanel, 'push', ...
                     'Position', [20 20 180 30], ...
                     'Text', 'Left Dispense (''A'')', ...
                     'FontSize', 14, ...
                     'FontWeight', 'bold', ...
                     'BackgroundColor', [0.3 0.7 0.9], ...
                     'ButtonPushedFcn', @(btn,event) leftDispense());
% uilabel(leftPanel, 'Position', [20 20 180 20], ...
%        'Text', 'Click "A" to dispense', ...
%        'HorizontalAlignment','center',...
%        'FontSize', 16);


% Right control panel
rightPanel = uipanel(fig, 'Title', 'Right Valve (Valve 2)', ...
                    'Position', [330 300 220 200], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Right Volume setting
uilabel(rightPanel, 'Position', [20 140 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);

rightDoseField = uieditfield(rightPanel, 'numeric', ...
                            'Position', [120 140 80 25], ...
                            'Value', DefaultDropSize, ...
                            'Limits', [0.1 1000], ...
                            'FontSize', 20, ...
                            'ValueChangedFcn', @(txt,event) updateValveTime('right'));

% Right number of drops setting
uilabel(rightPanel, 'Position', [20 100 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

rightDropField = uieditfield(rightPanel, 'numeric', ...
                             'Position', [120 100 80 25], ...
                             'Value', 1, ...
                             'Limits', [1 100], ...
                             'FontSize', 20);

% Right duration  setting
uilabel(rightPanel, 'Position', [20 60 100 20], ...
       'Text', 'Duration (ms):', ...
       'FontSize', 12);
ValveTime = BpodLiquidCalibration('GetValveTimes', DefaultDropSize, 2);

rightDurationField = uieditfield(rightPanel, 'numeric', ...
                            'Position', [120 60 80 25], ...
                            'Value', 1000*ValveTime, ...
                            'Limits', [0 1000], ...
                            'FontSize', 20, ...
                            'ValueDisplayFormat','%.0f',...
                            'Editable','off');
% Right dispense button
rightButton = uibutton(rightPanel, 'push', ...
                      'Position', [20 20 180 30], ...
                      'Text', 'Right Dispense (''D'')', ...
                      'FontSize', 14, ...
                      'FontWeight', 'bold', ...
                      'BackgroundColor', [0.3 0.7 0.9], ...
                      'ButtonPushedFcn', @(btn,event) rightDispense());
% uilabel(rightPanel, 'Position', [20 20 180 20], ...
%        'Text', 'Click "D" to dispense', ...
%        'HorizontalAlignment','center',...
%        'FontSize', 12);


% Counter display panel
countPanel = uipanel(fig, 'Title', 'Cumulative Dispensed Volume', ...
                    'Position', [50 70 500 200], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Left counter display
uilabel(countPanel, 'Position', [80 130 100 30], ...
       'Text', 'Left Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

leftCountLabel = uilabel(countPanel, 'Position', [200 130 100 30], ...
                        'Text', '0 μL', ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold', ...
                        'FontColor', [0 0.5 0]);

% Right counter display
uilabel(countPanel, 'Position', [300 130 100 30], ...
       'Text', 'Right Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

rightCountLabel = uilabel(countPanel, 'Position', [420 130 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0 0.5 0]);

% Total counter display
uilabel(countPanel, 'Position', [150 80 100 30], ...
       'Text', 'Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold', ...
       'FontColor', [0.5 0 0.5]);

totalCountLabel = uilabel(countPanel, 'Position', [250 80 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0.5 0 0.5]);

% Clear button
clearButton = uibutton(countPanel, 'push', ...
                      'Position', [200 30 100 30], ...
                      'Text', 'Clear Counters', ...
                      'FontSize', 12, ...
                      'BackgroundColor', [0.9 0.9 0.9], ...
                      'ButtonPushedFcn', @(btn,event) clearCounters());

% Status display
statusLabel = uilabel(fig, 'Position', [50 20 500 30], ...
                     'Text', 'Ready', ...
                     'FontSize', 12, ...
                     'HorizontalAlignment', 'center', ...
                     'BackgroundColor', [0.95 0.95 0.95]);

% Set window close callback - FIXED: using a nested function that can access fig
fig.CloseRequestFcn = @(src,event) closeGUI(fig);
fig.KeyPressFcn = @(src, event) onKeyPress(src, event);


function onKeyPress(~, event)
    % event.Key contains the name of the key pressed
    % event.Modifier contains any modifier keys (e.g., 'shift', 'control')
    keyName = event.Key;
    modifiers = strjoin(event.Modifier, '+');

switch keyName 
    case {'a'}
        leftDispense()
    case {'d'}
        rightDispense()
end
%     if isempty(modifiers)
%         statusLabel.Text = sprintf('You pressed: %s', keyName);
%     else
%         statusLabel.Text = sprintf('You pressed: %s + %s', modifiers, keyName);
%     end
end

% Left dispense function
function leftDispense()
    global leftCount totalCount
    global leftDoseField leftDropField leftCountLabel totalCountLabel statusLabel
    global leftDurationField 
    try
        dose = leftDoseField.Value;
        drops = leftDropField.Value;
        ValveTime_s = leftDurationField.Value ./ 1000;
        
        statusLabel.Text = 'Left dispensing in progress...';
        statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;
        
        % Call dispense function
%         Dispense(1, dose, drops);
        DispenseByDur(1, ValveTime_s, drops);
        
        % Update counters
        dispensedVolume = dose * drops;
        leftCount = leftCount + dispensedVolume;
        totalCount = totalCount + dispensedVolume;
        
        leftCountLabel.Text = [num2str(leftCount) ' μL'];
        totalCountLabel.Text = [num2str(totalCount) ' μL'];
        
        statusLabel.Text = sprintf('Left dispense complete: %.1f μL × %d', dose, drops);
        statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        statusLabel.Text = ['Error: ' ME.message];
        statusLabel.BackgroundColor = [1 0.8 0.8];
    end
end

% Right dispense function
function rightDispense()
    global rightCount totalCount
    global rightDoseField rightDropField rightCountLabel totalCountLabel statusLabel
    global rightDurationField 

    try
        dose = rightDoseField.Value;
        drops = rightDropField.Value;
        ValveTime_s = rightDurationField.Value ./ 1000;
        
        statusLabel.Text = 'Right dispensing in progress...';
        statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;
        
        % Call dispense function
%         Dispense(2, dose, drops);
        DispenseByDur(2, ValveTime_s, drops);
        
        % Update counters
        dispensedVolume = dose * drops;
        rightCount = rightCount + dispensedVolume;
        totalCount = totalCount + dispensedVolume;
        
        rightCountLabel.Text = [num2str(rightCount) ' μL'];
        totalCountLabel.Text = [num2str(totalCount) ' μL'];
        
        statusLabel.Text = sprintf('Right dispense complete: %.1f μL × %d', dose, drops);
        statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        statusLabel.Text = ['Error: ' ME.message];
        statusLabel.BackgroundColor = [1 0.8 0.8]; 
    end
end

% Clear counters function
function clearCounters()
    global leftCount rightCount totalCount
    global leftCountLabel rightCountLabel totalCountLabel statusLabel
    leftCount = 0;
    rightCount = 0;
    totalCount = 0;
    leftCountLabel.Text = '0 μL';
    rightCountLabel.Text = '0 μL';
    totalCountLabel.Text = '0 μL';
    statusLabel.Text = 'Counters cleared';
    statusLabel.BackgroundColor = [0.95 0.95 0.95];
end

% Close GUI function - FIXED: now accepts fig as input argument
function closeGUI(fig)
    % Stop Bpod protocol
    try
        RunProtocol('Stop');
    catch
        % Ignore errors
    end
    delete(fig);
end

function updateValveTime(whichValve)
    global leftDoseField leftDurationField
    global rightDoseField rightDurationField

    switch whichValve
        case 'left'
            newDropSize_ul = leftDoseField.Value;
            newValveTime_s = BpodLiquidCalibration('GetValveTimes', newDropSize_ul, 1);
            leftDurationField.Value = 1000*newValveTime_s;
        case 'right'
            newDropSize_ul = rightDoseField.Value;
            newValveTime_s = BpodLiquidCalibration('GetValveTimes', newDropSize_ul, 2);
            rightDurationField.Value = 1000*newValveTime_s;

    end
end